//
//  MMServiceID.h
//  MMCoreServices
//
//  Created by Mark on 2018/3/18.
//  Copyright © 2018年 Mark. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 * Each MMservice must have its own identifier, cos' the most tasks are
 * asynchronous, some tasks may need to access to MMService even in the
 * underlayer, such as the important property MMService.invalid, now the
 * MMServiceID will be your key to touch the MMService.
 *
 * Default identifier and serviceKey will be a uuid string, but you'd better
 * replace the read-only serviceKey property in MMServiceID to recognize
 * MMService more easily.
 *
 * It passes through MMService, then MMOperation, & then MMRequest.
 */
@protocol MMServiceID <NSObject>
@required
@property (nonatomic, strong) NSString *identifier; ///< Default is a uuid
@property (nonatomic, strong, readonly) NSString *serviceKey;   ///< Generated by some other properties, default is identifier, & it will be identifier in most case.
@end

@interface MMServiceID : NSObject <MMServiceID>
@end
