//
//  MMServiceID.h
//  MMCoreServices
//
//  Created by Mark on 2018/3/18.
//  Copyright © 2018年 Mark. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 * Each MMservice must have its own identifier, cos the most task are
 * asynchronous, some tasks may need to access the property of MMService even
 * in the underlayer, such as the important property MMService.invalid, now the
 * MMServiceID will be your key to touch the MMService.
 *
 * It passes through MMService -> MMOperation -> MMRequest
 */
@protocol MMServiceID <NSObject>
@required
@property (nonatomic, strong) NSString *identifier; ///< Default is a uuid
@required
@property (nonatomic, strong, readonly) NSString *serviceKey;   ///< Generated by some other properties, default is identifier, & it is in most case.
@end

@interface MMServiceID : NSObject <MMServiceID>
@end
